---

- include: install_from_source.yml
  when: telegraf_install_from_source
  tags:
    - telegraf

- include: install_from_package.yml
  when: not telegraf_install_from_source
  tags:
    - telegraf
    
- name: "Copy configuration file"
  action: template
          src=telegraf.conf.j2
          dest="{{ telegraf_conf_dir }}/telegraf.conf"
          owner=root
          group=root
          mode=644
  notify: "Restart Telegraf"
  tags:
    - telegraf
